# Generated by Django 5.1.3 on 2024-11-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweeter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='name',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
